### ISSUE TITLE
React.requireNativeComponent undefined

### ISSUE THREAD

**Issue by jaulz** [umhan35/react-native-search-bar#1]
It seems that React.requireNativeComponent is undefined. Do I need to include other libraries as well? Could you please go into detail which files need to be linked?

**Comment by armcast** [comment]
I followed this [guide](http://facebook.github.io/react-native/docs/linking-libraries.html) to linking libraries with projects. I linked "RNSearchBar.xcodeproj" found in the node-modules folder of my project directory and linked the "libRNSearchBar.a" library with my main project binary. 

After doing this, I still get the same error you are describing -- "undefined is not a function (evaluating 'React.requireNativeComponent('RNSearchBar', null)"

Any ideas?

**Comment by umhan35** [comment]
That's wird. I'll create a minimum react native project and hopefully get back to you guys soon.

**Comment by umhan35** [comment]
I just updated the dependency react-native to its latest stable version 0.5.0. `React.requireNativeComponent` was not available in an earlier version... The change is pushed to npm.

**Comment by armcast** [comment]
Ah  ok, so my version of react-native is out of date. Excuse my ignorance, but how would I go about updating to version 0.5.0?

Thanks for the response by the way

**Comment by umhan35** [comment]
Try this:
```
npm install react-native@latest --save
npm install react-native-search-bar@latest --save
```

**Comment by armcast** [comment]
That did the trick. Thank you very much.

**Comment by umhan35** [comment]
No problem. :smile: 

The things discussed here is also documented in README.md.
