### ISSUE TITLE
could you please add support for showsCancelButton.

### ISSUE THREAD

**Issue by pgmemk** [umhan35/react-native-search-bar#10]
Thank you for the **SearchBar** :). 
Could you please add **showsCancelButton** support to be able to hide it

**Comment by umhan35** [comment]
It's supported. Take a look here: https://github.com/umhan35/react-native-search-bar/blob/a2fdd8946e55bfe8dc8ea3cb310c3ef12fdcec61/SearchBar.coffee#L15
