### ISSUE TITLE
Cannot read 'ComponentHeight' of undefined 

### ISSUE THREAD

**Issue by andyfen** [umhan35/react-native-search-bar#101]
"react": "15.3.2",
    "react-native": "^0.37.0",
    "react-native-search-bar": "^2.16.0",

<img width="370" alt="screen shot 2016-11-19 at 09 37 15" src="https://cloud.githubusercontent.com/assets/5710962/20457246/ecc863e2-ae3b-11e6-99c2-e9799707039d.png">

**Comment by DonovanCharpin** [comment]
Same issue with react-native 0.37.0

**Comment by rikur** [comment]
react-native link react-native-search-bar

**Comment by andremsantos** [comment]
I had the same issue. rebuild the app.

`react-native run-ios`

**Comment by RyanAtViceSoftware** [comment]
I'm having the same issue in RN 0.40. Linking and rebuilding didn't help me.

**Comment by villancikos** [comment]
Thanks a lot! The link rebuilding worked!
