### ISSUE TITLE
 Placeholder text how to align to left icon

### ISSUE THREAD

**Issue by Aaaaaashu** [umhan35/react-native-search-bar#103]
![image](https://cloud.githubusercontent.com/assets/3678166/20621214/6c68b9ac-b338-11e6-8277-fc6f96f163cc.png)

I didn't find any suitable props to change placeholder text style.

Version:
"react-native-search-bar": "^2.16.0"
"react-native": "^0.36.0"

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern in the latest version, please create a new issue. Thanks
