### ISSUE TITLE
Can not compile my files

### ISSUE THREAD

**Issue by CarmeloXue** [umhan35/react-native-search-bar#108]
I add the xcode project to my libraries, and add build Phases, but when i try to build my project,I got this error

![image](https://cloud.githubusercontent.com/assets/24514156/22181040/e087cac8-e0bd-11e6-9c6f-08238c32adba.png)
what should i do to fix this

**Comment by CarmeloXue** [comment]
some times meet this error

![image](https://cloud.githubusercontent.com/assets/24514156/22181382/4542f6ec-e0c6-11e6-8b93-ccf3a17c56e0.png)

**Comment by iRoachie** [comment]
Are you using react native 0.40? The current project isn't compatible with React Native v0.40, since the maintainer hasn't updated in a long time. You can get a working version from Freddy's fork. #105

**Comment by CarmeloXue** [comment]
@iRoachie OK Problem solved many thx
