### ISSUE TITLE
Got a deadlock when I use This package

### ISSUE THREAD

**Issue by CarmeloXue** [umhan35/react-native-search-bar#109]
Follow the instruction in the closed issue ,i use Freddy's fork for my App because my react native is 0.40.
And I can add a search bar into my app. Sometimes I can trigger it by using react-native run-ios, but it's performance  is low and i can't open a remote debugger. But when I use Xcode to built my app, i got this 

![image](https://cloud.githubusercontent.com/assets/24514156/22193001/983068d2-e173-11e6-984f-21ee40b3d26e.png)

the info said there is a deadlock . But I dont know how to fix this.

**Comment by kh1990** [comment]
+1 same issue, been using xcode to debug but its a pain...

**Comment by kh1990** [comment]
Apparently this is more of a core issue with RN rather than the library...see here: https://github.com/facebook/react-native/issues/11196

**Comment by martsie** [comment]
This cost me a night of development till I could trace it back to to react-native-searchbar ... it's a really difficult thing to debug unless you actually run the app using xcode, check the logs, and google lands you on this page.

Until this bug is fixed I think it's best to steer developers away from using this module unless they don't need access to their debugger.

**Comment by kh1990** [comment]
Update: I noticed the deadlock only occurs for me when I am working on a branch. Each time I submit a pull request and merge into the master, the deadlock is resolved. Maybe this will help some of you.

**Comment by mithunm93** [comment]
In case anyone comes to this thread in search of the solution, the link @kh1990 posted above now contains the answer: https://github.com/facebook/react-native/issues/11196#issuecomment-298376877

**Comment by chrise86** [comment]
@mithunm93 if anything, the answer posted there makes it worse for me - I start getting all sorts of errors 😞

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern in the latest version, please create a new issue. Thanks
