### ISSUE TITLE
Cannot read property "componentHeight" of undefined

### ISSUE THREAD

**Issue by owzzz** [umhan35/react-native-search-bar#11]
Getting an error when including a basic example of the search bar in my project.

It's not finding "NativeModules.RNSearchBarManager.ComponentHeight".

Line 40: SearchBar.js

```
<SearchBar placeholder='Search' onChangeText={this.createEvent}/>
```

**Comment by umhan35** [comment]
Do you have the latest version of `react-native-search-bar`?

What's your version of rn (react-native)?

**Comment by umhan35** [comment]
There is a breaking API change in rn 0.8. I just pushed a new version to npm, which should solve the problem.

**Comment by Tom29** [comment]
Still get this error on version 3.0.0
