### ISSUE TITLE
Keyboard not appearing

### ISSUE THREAD

**Issue by circuit-monkey** [umhan35/react-native-search-bar#110]
I've created the following component: 

```
import React, { Component } from 'react';
var SearchBar = require('react-native-search-bar');

class Search extends React.Component {
  componentDidMount() {
    this.refs.searchBar.focus();
  }
  render() {
    return (
      <SearchBar
        style={{ height: 50, width: 415 }}
        ref="searchBar"
        placeholder='Select verb'
        textFieldBackgroundColor='white'
      />
    );
  }
}

export default Search;
```

And it works - except that the keyboard does not appear when doing a search. 

What might I be doing wrong exactly?

**Comment by tedjames** [comment]
I'm having the same issue as well :/

**Comment by tedjames** [comment]
Lol.... Idk why I didn't realize this earlier but the keyboard isn't supposed to show up in the simulator! Run the app on your phone and the keyboard will pop up.

**Comment by edo1493** [comment]
Just press CMD + K and the keyboard will show up. : )

**Comment by tedjames** [comment]
Aha! Thanks for the tip 👍
