### ISSUE TITLE
Tab bar gets clicked

### ISSUE THREAD

**Issue by edo1493** [umhan35/react-native-search-bar#111]
Hi, 
I am using this component along side a tab bar. Whenever I click the "search button", the tab bar element underneath gets clicked too. This behaviour doesn't happen when I open the keyboard through a TextInput. I am wondering if this is related to the component itself and if anyone has seen this behaviour. 

I am currently on "react-native": "^0.40.0".

**Comment by allardvdo** [comment]
I had a similar problem.

See https://github.com/umhan35/react-native-search-bar/issues/124 for work-around.

**Comment by iRoachie** [comment]
Hey @samdiaz new maintainer here. We recently release v3.1.0, if this is still happening then ping me to reopen this issue or create a new issue.
