### ISSUE TITLE
undefined is not an object (evaluating \'NativeModules.RNSearchBarManager.ComponentHeight\')

### ISSUE THREAD

**Issue by WhynoChinese** [umhan35/react-native-search-bar#112]
undefined is not an object (evaluating \'NativeModules.RNSearchBarManager.ComponentHeight\')

**Comment by beormalte** [comment]
This worked for me:
react-native link
xcode - products > clean
stop project and start it again

**Comment by smtlaissezfaire** [comment]
I did the manual linking that the docs tell you to do, and then rebuilt in xcode, and all worked!

**Comment by dhioetanasti** [comment]
i did the manual linking and there is this error -> 'React/RCTViewManager.h' file not found

**Comment by iRoachie** [comment]
Hey new maintainer here. We just published v3.1.0. If this is still a problem in the latest version, please create a new issue or ping me to reopen this one. Thanks

**Comment by alexlevy0** [comment]
Same issue with RN 0.55.4 and react-native-search-bar@3.4.1

**Comment by iRoachie** [comment]
@alexlevy0 Did you try the solution above? This is often a problem when the library is not linked correct.y

**Comment by eveningkid** [comment]
Hey,

I have the same issue and can't manage to have it working.
After going through the manual linking, here's what I get:

![image](https://user-images.githubusercontent.com/7188494/45246116-d97c3280-b2ff-11e8-8aad-0d58977e1c7a.png)

![image](https://user-images.githubusercontent.com/7188494/45246094-c49f9f00-b2ff-11e8-9fad-a422d5c37da0.png)

It keeps failing when I build it:

![image](https://user-images.githubusercontent.com/7188494/45246136-f3b61080-b2ff-11e8-92ae-90d5eb8d56d3.png)

I really hope I could use this package, if anyone knows what could be the issue there...

Thank you very much!

**Comment by iRoachie** [comment]
Did you rebuild the project after installing and linking?

**Comment by eveningkid** [comment]
When I try to build in Xcode, it fails. After linking again and running it on the device, I still get the `ComponentHeight` exception showing up. 

Have I missed something?

**Comment by iRoachie** [comment]
Can you link to your project? I have no problems setting up a new project.
