### ISSUE TITLE
[Question] Return Key

### ISSUE THREAD

**Issue by gperdomor** [umhan35/react-native-search-bar#113]
It's possible change the "Search" text from Return Key to "Done"?

**Comment by iRoachie** [comment]
Hey @gperdomor this is implemented in https://github.com/umhan35/react-native-search-bar/pull/133/commits/a1811f2b5b518c052507ada8b9af6d3f64437b5e and is scheduled to be in the next release

**Comment by iRoachie** [comment]
Released in [v3.2.0](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.2.0). You can use the `returnKeyType` prop.
