### ISSUE TITLE
Setting textFieldBackgroundColor changes the height

### ISSUE THREAD

**Issue by samdiaz** [umhan35/react-native-search-bar#115]
The height gets changed to 34, when it should be 30.

See lines 80-85 in RNSearchBarManager.m.

    // Add a clip before drawing anything, in the shape of an rounded rect
    [[UIBezierPath bezierPathWithRoundedRect:CGRectMake(0,0, 34, 34)
                                cornerRadius:5.0] addClip];`

Happy to submit a PR fixing this.

**Comment by iRoachie** [comment]
Hey @samdiaz new maintainer here. We recently release [v3.1.0](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.1.0), if this is still happening then ping me to reopen this issue or create a new issue.
