### ISSUE TITLE
Error when archiving and also when building as a release scheme.

### ISSUE THREAD

**Issue by piyushchauhan2011** [umhan35/react-native-search-bar#12]
I'm getting this error when building it as a release build. `Product` -> `Scheme` -> `Edit Scheme` and mark as `release` build. 

You can also use `Product` -> `Archive` and it will not build a package and give the error.

![screen shot 2015-07-28 at 11 31 21 am](https://cloud.githubusercontent.com/assets/693487/8921665/5304d874-351c-11e5-9fe1-d7a98b42217f.png)

**Comment by umhan35** [comment]
That file is inside the `React` library. Did you link it to your project?

<img width="259" alt="screen shot 2015-07-28 at 10 46 43 am" src="https://cloud.githubusercontent.com/assets/3271612/8936105/009bcb34-3516-11e5-9693-3d10e274efdc.png">

**Comment by piyushchauhan2011** [comment]
Still getting the same error after building the release.

**Comment by umhan35** [comment]
Sorry, I also tried the `release` scheme in the [SearchBarExample](https://github.com/umhan35/react-native-search-bar/tree/master/SearchBarExample) project and it has the same issue. I couldn't figure out why...

But you can try to open an issue at react-native(https://github.com/facebook/react-native/issues).

**Comment by piyushchauhan2011** [comment]
:+1: I will post it.

**Comment by umhan35** [comment]
Solve in PR #14
