### ISSUE TITLE
Warning: Native component for "RNSearchBar" does not exist

### ISSUE THREAD

**Issue by changjianhong** [umhan35/react-native-search-bar#122]
react-native-cli: 2.0.1
react-native: 0.44.0
react-native-search-bar 3.0.0

**Comment by ozburo** [comment]
You need to link the binaries:

`react-native link`

And recompile:

`react-native run-ios`

**Comment by benstoehr** [comment]
If you are in a "create-react-native-app" how do you fix this issue? 

There is no way to link the libraries because you cannot run "react-native link" in a CRNA directory. 

I am using Expo and a physical iPhone.

**Comment by iRoachie** [comment]
There’s no way to use this library with CRNA or Expo since it’s a native module. You can try using the SearchBar from react-native-elements if you want a JS only search bar
