### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by vonovak** [umhan35/react-native-search-bar#128]
hi @umhan35 I'd like to ask if you plan on maintaining the repo, or if you're looking for some maintainers. There are currently several issues that make it not possible to use the package with newest RN. :/ The PRs are already there but not being merged/reviewed.
thanks :)

**Comment by jxom** [comment]
https://github.com/localz/react-native-searchbar is a very good alternative, and supports Android too!

**Comment by vonovak** [comment]
@umhan35 can you please comment on this? Thanks :)

**Comment by jxom** [comment]
@vonovak, more flexibility, actively maintained, try it out and see for yourself. :)

**Comment by Benjamin-Dobell** [comment]
Hmm, I actually thought based on the dead homepage and lack of Github activity that it was possible @umhan35 may have passed away - it does happen occasionally. However, @umhan35's Facebook account seems to have been active in October, so it's possible he's just decided to step aside from open source for a while. Perfectly acceptable (although a public announcement would have been appreciated), but it may be time for the community to take over the maintenance burden, fork repos and upload alternate NPM modules.

**Comment by vonovak** [comment]
Since @umhan35 is not responding, I have reached out to npm to claim the package name. If that goes through, the community may continue the development in a fork and publish under the same npm name. If anyone is interested in being a maintainer, let me know.

**Comment by umhan35** [comment]
👎 I'm not passing away. I was still working for your guys this Jan for free. I'm busy with my PhD now. I'll try to contact @iRoachie if he'd like to be a collaborator of this repo and I'll add him to npm too.
