### ISSUE TITLE
onCancelButtonPress and onSearchButtonPress not working in RN 0.51

### ISSUE THREAD

**Issue by ocarreterom** [umhan35/react-native-search-bar#136]
Callbacks `onCancelButtonPress` and `onSearchButtonPress` are not working in:
- RN 0.51.0
- react-native-search-bar 3.2.0
- iOS 11.2 (simulator)

I don't know if this warning affects:
> Module RNSearchBarManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by iRoachie** [comment]
Hey @ocarreterom your project is probably referencing an older version of the library as I just created a new project and had no issues.

Try these steps:
`react-native unlink react-native-search-bar`
`npm install --save react-native-search-bar@latest`
`react-native link react-native-search-bar`

**Comment by ocarreterom** [comment]
Thanks @iRoachie . I removed and linked again `libRNSearchBar.a` and now works fine.

**Comment by iRoachie** [comment]
Great! Glad I could help!

**Comment by bathach95** [comment]
this happened again on v 3.5.1
