### ISSUE TITLE
Unexpected color change

### ISSUE THREAD

**Issue by EclipticWld** [umhan35/react-native-search-bar#141]
Hey. I wanted to change barTintColor on '#2196f3' but factually it becomes '#2a92e6'. What's wrong with that?

 ![f](https://i.imgur.com/jPxCfsy.png)

**Comment by EclipticWld** [comment]
@iRoachie

**Comment by iRoachie** [comment]
Hey, will check it tonight when I get in

**Comment by EclipticWld** [comment]
@iRoachie thank you!

**Comment by EclipticWld** [comment]
I suddenly realized that search bar has opacity somehow probably because of [RNSearchBarManager.m#L84](https://github.com/umhan35/react-native-search-bar/blob/master/ios/RNSearchBarManager.m#L84)

**Comment by iRoachie** [comment]
That opacity tint is actually just for the text field so it doesn't affect the bar. 
Not sure what's up though, it seems to be fine in my tests.

![simulator screen shot - iphone 6 - 2018-01-13 at 23 15 30](https://user-images.githubusercontent.com/5962998/34912427-b1f2b304-f8b7-11e7-9bec-7babc2aa5a3c.png)

**Comment by EclipticWld** [comment]
hm. Ok. I found a workaround on my side by setting background underlayer.
