### ISSUE TITLE
Cutomize cancel button text

### ISSUE THREAD

**Issue by EclipticWld** [umhan35/react-native-search-bar#142]
I'm not familiar with iOS programming but I think it would be cool to have a parameter for customizing cancel button. 

```obj-c
- (void)searchBarTextDidBeginEditing:(UISearchBar *)searchBar
{
    /* when user start editing in search bar this method will display cancel button and disable the autocorrection functionality */

    srcbar.showsCancelButton = YES;

    for (UIView *subView in searchBar.subviews) {
        if ([subView isKindOfClass:[UIButton class]]) {
           UIButton *cancelButton = (UIButton*)subView;

            [cancelButton setTitle:@"hi" forState:UIControlStateNormal];
        }
    }
    srcbar.autocorrectionType = UITextAutocorrectionTypeNo;

}
```
![](http://i.stack.imgur.com/vDhmQ.png)

[Found here](https://codedump.io/share/PVdIrhQu4p12/1/ios-change-the-title-of-cancel-button-in-uisearchbar)

**Comment by iRoachie** [comment]
Hey that's a brilliant suggestion! I see it being particularly useful for wanting to use other languages other than English. I just added it on `next`, let me know if it works for you.

**Comment by EclipticWld** [comment]
Thanks 👍
