### ISSUE TITLE
Don't support android?

### ISSUE THREAD

**Issue by wudashuaige** [umhan35/react-native-search-bar#146]
undefined is not an object

**Comment by iRoachie** [comment]
It’s only for iOS.

**Comment by Noitidart** [comment]
Is there chance for Androdi support? Android also has a search view called `android.widget.SearchView`.

We see NativeScript has done this here:

https://nativescript-vue.org/en/docs/elements/components/search-bar/

**Comment by mtzfactory** [comment]
Yeah, that would be very interesting...

**Comment by iRoachie** [comment]
Released in [v3.5.0](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.5.0)

**Comment by Noitidart** [comment]
Thank you Kyle!!!!
