### ISSUE TITLE
showsCancelButton property has no effect, cancel button is always visible while editing

### ISSUE THREAD

**Issue by rudyryk** [umhan35/react-native-search-bar#148]
I'm using the following code to render search bar

```jsx
<SearchBar
  ref='nativeBar'
  showsCancelButton={false}
  onChangeText={(text) => this.props.onChangeText(text)}
/>
```

but still getting "Cancel" button rendered:

<img width="374" alt="cancel-button" src="https://user-images.githubusercontent.com/4500/37571489-55340bca-2b0e-11e8-8473-34955431e625.png">

**Comment by iRoachie** [comment]
You have to set `showsCancelButtonWhileEditing` to false

**Comment by rudyryk** [comment]
@iRoachie Thank you, that worked! Actually I tried it first but something went wrong (don't know exactly what) but finally everything is OK.
