### ISSUE TITLE
breaks on 0.9.0 due to EventDispatcher: sendTextEventWithType method

### ISSUE THREAD

**Issue by jsierles** [umhan35/react-native-search-bar#15]
sendTextEventWithType now requires a fourth parameter: nativeEventCount.

See 

https://github.com/facebook/react-native/commit/961c1eb42904a4d5516fd7939ba14bc0625309d3

**Comment by umhan35** [comment]
Ah... breaking change again...

It seems you know the solution. Would you mind sending a pull request?

**Comment by jsierles** [comment]
I see a fourth parameter is required, but it's not clear to me yet what nativeEventCount means or how to generate the right value. I'll look into it when I have some time.

**Comment by umhan35** [comment]
How did you install the 0.9.0-rc through npm? It doesn't seem published on npm...

**Comment by jsierles** [comment]
this works for me: npm install --save react-native@0.9.0-rc

**Comment by coderdave** [comment]
Any solutions or workarounds for this? My build is also failing on 0.9.0 and getting these errors.

**Comment by jonathancochran** [comment]
Having the same issue as @coderdave

**Comment by alejomendoza** [comment]
Same issue here, breaking my app. I would try to help but I'm very recent to Objective-C.

![issue](https://cloud.githubusercontent.com/assets/5351127/9374900/4759d7f8-46c0-11e5-9c16-cf75d645b950.png)

**Comment by umhan35** [comment]
I'll see if I can solve it tomorrow. The bad news is that I'm using OS X El Capitan now and Xcode became unusable...

**Comment by chengs** [comment]
I make a little change to let it work.

**Comment by umhan35** [comment]
Thanks to @chengs , a working version with 0.9 is pushed to `npm` just now.
