### ISSUE TITLE
Error in Height

### ISSUE THREAD

**Issue by rincethomas** [umhan35/react-native-search-bar#154]
Type Error Undefined is not an object. react native. RNSearchBarManager.ComponentHeight

**Comment by iRoachie** [comment]
Are you using expo?

**Comment by rincethomas** [comment]
No

**Comment by iRoachie** [comment]
Couldn't replicate this. I just created a new project and it worked as normal.

1. `react-native init Test`
2. `cd Test`
3. `npm install react-native-search-bar && react-native link react-native-search-bar`
4. `react-native run-ios`

Works as expected.
