### ISSUE TITLE
[iOS 13] Text and icon's color is different in darkmode

### ISSUE THREAD

**Issue by KostasKostogloy** [umhan35/react-native-search-bar#166]
iOS 13 introduced dark mode (https://support.apple.com/en-us/HT210332).

If the user has it enabled the appearance of the searchbar changes (icon and text color):
![image](https://user-images.githubusercontent.com/7452129/68024633-519b7980-fcb3-11e9-919a-37270ccad3e4.png)

I am aware that we can change the default text color with the `textColor` prop but how can we change the icon (magnifying glass) color?

**Comment by iRoachie** [comment]
Isn't this the correct behaviour? This is what the settings from iOS shows

![image](https://user-images.githubusercontent.com/5962998/68032055-39b3fd80-fc93-11e9-82f2-c6d03c7e1304.png)

And this is this library:

![image](https://user-images.githubusercontent.com/5962998/68032294-c3fc6180-fc93-11e9-9005-83da49e00abb.png)

**Comment by KostasKostogloy** [comment]
@iRoachie We don't use dark mode on our app and as a result the lighter gray icon fades (as you can see on the screenshot). 

If there's no way to opt out of dark mode adjustments on the app's level, we should at least be able to override the icon to keep it consistent regardless of user using darkmode or not.

**Comment by iRoachie** [comment]
As far as I know, the icon is an image https://stackoverflow.com/questions/27014529/how-to-change-the-color-of-the-uisearchbar-icon. If you don't use dark mode in your app you can simply opt-out of it. https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13

**Comment by KostasKostogloy** [comment]
@iRoachie I see. I must opt-out from darkmode from my app. Thanks for pointing me to the right direction 🍻
