### ISSUE TITLE
onCancelButtonPress not working in 2.0.0

### ISSUE THREAD

**Issue by coderdave** [umhan35/react-native-search-bar#20]
The `onCancelButtonPress` property callback isn't working anymore for me with 2.0.0.

is there something I need to do to upgrade?

**Comment by coderdave** [comment]
Ok, I see the PR to fix this: https://github.com/umhan35/react-native-search-bar/pull/19

**Comment by jhabdas** [comment]
@umhan35 would you be able to close this and merge #19 assuming it's good to go?

**Comment by umhan35** [comment]
@jhabdas Thanks for @ me. I'll try to merge it today.

**Comment by jhabdas** [comment]
Np. Tried fix locally with success.

**Comment by umhan35** [comment]
Just pushed 2.0.1 to npm. :)

**Comment by jhabdas** [comment]
You da man!

**Comment by jhabdas** [comment]
Tested `2.1.0` package and it's working well. Thanks again!
