### ISSUE TITLE
onPress event is not firing

### ISSUE THREAD

**Issue by sercanov** [umhan35/react-native-search-bar#22]
I put a log on _onPress function in SearchBar.js but even this line is not firing

**Comment by nautical** [comment]
_onChange event gets fired but _onPress is not getting fired .

**Comment by nautical** [comment]
My mistake , recompiling the module worked for me .

**Comment by umhan35** [comment]
@nautical so `onPress` is working for you?

**Comment by nautical** [comment]
@umhan35  Yes It is , what is the error you are getting ?
