### ISSUE TITLE
How to change the word 'Cancel' that hide in the right ?

### ISSUE THREAD

**Issue by NixusCN** [umhan35/react-native-search-bar#23]
![image](https://cloud.githubusercontent.com/assets/4592706/10069653/28a0f6ca-62e0-11e5-8c43-2b3b22e2314e.png)
I want to change the word `Cancel` to `取消`,how can I to do ?
Thanks very much.

**Comment by NixusCN** [comment]
When I click the search bar, the content moves slowly in the input.
How can I change the move speed ?

**Comment by umhan35** [comment]
You need to change objective-c code to change the Cancel button text: http://stackoverflow.com/questions/28990854/change-uisearchbar-cancel-button-text-in-ios-8. Check out recent pull requests to see how to do this. I assume if you change the language of iOS, the text of cancel button will become the native language of Cancel.

**Comment by umhan35** [comment]
> When I click the search bar, the content moves slowly in the input.
How can I change the move speed ?

It's not slow for me. it's probably slow in the simulator but not on real devices.

**Comment by NixusCN** [comment]
@umhan35 Thanks very much
