### ISSUE TITLE
Programmatically focus search bar

### ISSUE THREAD

**Issue by Mokto** [umhan35/react-native-search-bar#24]
Hi,

Is there any way to programmatically focus the search bar ?

I want to automatically focus it when it appears.

Thanks.

**Comment by nautical** [comment]
@Mokto  Got any solution ? :+1:

**Comment by Mokto** [comment]
@nautical 

I am a web developper, and never created objective-c code, , so no ^^

I will ask this to my iOS developer next week, I will keep you in touch.

**Comment by nautical** [comment]
I have not looked into the binding of Obj-C and react native framework , will look over that in weekend and submit a request , but for now , in case you want it as default you can do something like
          [self becomeFirstResponder];
in RNSearchBar.m (initWithEventDispatcher function before return) . It will focus on search and activate it whenever you call search , if thats your required demand .

**Comment by Mokto** [comment]
Oh well...

Just did it :dancer:

**Comment by Mokto** [comment]
Thank you for the tip anyway :)

**Comment by nautical** [comment]
Ok :+1:

**Comment by JedWatson** [comment]
@Mokto @nautical is there a similar method that can be used to implement `blur` as well? (for #32)

**Comment by JedWatson** [comment]
EDIT - sorry @Mokto just saw your PR #28. Thanks, hope these get merged soon :)

**Comment by Mokto** [comment]
:)

**Comment by Mokto** [comment]
It's been 11 days since the first PR has been uploaded. I hope that too :P

**Comment by arilitan** [comment]
please merge this commit @umhan35 thanks!

**Comment by umhan35** [comment]
Soved by `this.refs.searchbar.blur();`
