### ISSUE TITLE
showsCancelButton not working with false value

### ISSUE THREAD

**Issue by Mokto** [umhan35/react-native-search-bar#26]
Hi,

I don't know if this is a bug or if this is normal.

showsCancelButton={false} has a wrong behavious. In my opinion :
* __no attribute__ : should show cancel only on focus => OK
* __showsCancelButton={true}__ : should show the cancel button even if not focus => OK
* __showsCancelButton={false}__ : should never show the cancel button => NOT OK.

What do you think ?

**Comment by vmagro** [comment]
I filed a PR to fix this here https://github.com/umhan35/react-native-search-bar/pull/30

**Comment by adaojunior** [comment]
+1 same issue here

**Comment by umhan35** [comment]
Closed as #30 is merged.
