### ISSUE TITLE
How to change the 'cancel' color and fonts?

### ISSUE THREAD

**Issue by eyaleizenberg** [umhan35/react-native-search-bar#27]
Hi,
First of all, very cool component!
Second, can I use a different font throughout the component?

Thanks!

**Comment by SirBryan** [comment]
In RNSearchBarManager.m, I changed RCT_CUSTOM_VIEW_PROPERTY(textColor...) by adding the ability to change the UIBarButtonItem's (Cancel button's) appearance:
```objective-c
RCT_CUSTOM_VIEW_PROPERTY(textColor, UIColor, RNSearchBar)
{
    if([RCTConvert UIColor:json]) {
       [[UITextField appearanceWhenContainedIn:[RNSearchBar class], nil] setDefaultTextAttributes:@{NSForegroundColorAttributeName:[RCTConvert UIColor:json]}];
// Make Cancel button same color as text
        [[UIBarButtonItem appearanceWhenContainedIn:[RNSearchBar class], nil]
         setTitleTextAttributes:@{NSForegroundColorAttributeName: [RCTConvert UIColor:json]}
         forState:UIControlStateNormal];
// End 
    }
}
```

**Comment by ochengo** [comment]
Hi @SirBryan, how did you get that bit of code to work? Is that supposed to change the color of the 'x' button on the right?

**Comment by SirBryan** [comment]
It changes the "Cancel" text to match the chosen tint.  In my case it's now off-white instead of blue to match the rest of the UI.  



(Sent while mobile)

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
