### ISSUE TITLE
Programmatically blur search bar

### ISSUE THREAD

**Issue by JedWatson** [umhan35/react-native-search-bar#32]
Similar to #24, it would be valuable to be able to `.blur()` the search bar to hide the keyboard, as you can with the React Native `TextInput` component.

**Comment by JedWatson** [comment]
Just realised there's already a PR for this! #28

**Comment by jhabdas** [comment]
See also https://github.com/umhan35/react-native-search-bar/issues/5

**Comment by jhabdas** [comment]
Is it necessary, or even desirable, to control user intent within the context of the `SearchBar` component? Seems risky given there may be a number of different use cases, though it might be a nice option to have if controllable by prop. Looks like the current way people are handling `TextInput` blur is to wrap the input with a `ScrollView` [as described](http://stackoverflow.com/a/31504085/712334) on SO.

**Comment by JedWatson** [comment]
Thanks for pointing that out @jhabdas. I'll see if I can get the `RCTUIManager.blur(React.findNodeHandle(this.refs.searchbar))` solution to work until #28 is merged.

@umhan35 regarding whether this is actually useful functionality, I'm implementing a "search on submit" pattern (not search as you type) so I want to be able to blur the field (and hide the keyboard) in my handler for the `onSearchButtonPress` event. This is different to the case mentioned in #5 where the `keyboardDismissMode` prop of `ScrollView` could be used.

The `TextInput` component exposes a `blur()` method that can be used for reasons like this, it would be nice if `react-native-search-bar` did the same.

**Comment by jhabdas** [comment]
@JedWatson even with #28 it's not clear - to me at least - how to utilize the blur method to programmaticly blur the component. But your snippet grabbing the field by ref looks promising. If it works I'll add another example to this repo showing how to use it with a ListView with basic filtering behavior for others.

**Comment by jhabdas** [comment]
@JedWatson Thanks. Based on your response I was able to use your fork to successfully blur the `SearchBar` on list item select from an associated search results list. It was easier than expected. For those looking to do the same here're some high-level instructions to make it happen:

- Until #28 #29 are merged and a new NPM module released, update `package.json` to go after the fork `inProgress-team/react-native-search-bar` instead of this component.
- Assign a `ref` prop to the `SearchBar` component, e.g. `ref="searchbar"`
- Then, in the `onPressRow` handler for the corresponding search results `ListView` get the node handle by reference and pass it as input to the native module blur method, e.g.

```js
_onPressSearchResult(searchData: Object) {
  NativeModules.RNSearchBarManager.blur(React.findNodeHandle(this.refs.searchbar));
    this.setState({
      isOverlayVisible: false,
      searchData: searchData,
    });
}
```

**Comment by jhabdas** [comment]
Took the `2.5.0` update and the `blur` method introduced by @Mokto in #28 looks to satisfy this issue. @JedWatson there's also an `onBlur` callback in the latest release on NPM. Can this be closed?

**Comment by eyaleizenberg** [comment]
using 2.5.0 I still can't figure out how to blur after pressing the 'search' button...

**Comment by jhabdas** [comment]
@eyaleizenberg how's this?

```js
import React, { Component, NativeModules } from 'react-native';

let {
  RNSearchBarManager
} = NativeModules;

const SEARCH_BAR_REF = 'searchbar';

MyComponent extends Component {
  render() {
    return (
      <View style={styles.container}>
        <SearchBar
          ref={SEARCH_BAR_REF}
          placeholder='Search'
          onSearchButtonPress={this._onPressSearchButton.bind(this)}
        />
      </View>
    )
  }

  _onPressSearchButton() {
    RNSearchBarManager.blur(React.findNodeHandle(this.refs[SEARCH_BAR_REF]));
  }
}
```

**Comment by swain** [comment]
How can SearchBar resignFirstResponder automatically when touch outside, just like TextInput do?

**Comment by rohitgoyal** [comment]
Any solution to it yet?

**Comment by jhabdas** [comment]
@rohitgoyal try my solution above, let us know how it goes

**Comment by rohitgoyal** [comment]
@jhabdas Got it resolved with simple
this.refs.searchbar.blur();
Thanks anyways. :)

**Comment by umhan35** [comment]
Yeah, I guess I merged someone's pr and you can just use `this.refs.searchbar.blur();` now.

**Comment by shailesh92** [comment]
please help not working like his.refs.searchbar.blur()
