### ISSUE TITLE
Problem to position UISearchBar

### ISSUE THREAD

**Issue by JeanLebrument** [umhan35/react-native-search-bar#33]
Hello,

I have some troubles when I want to integrate this package to my project. For some reasons, I have to specify `marginTop` and `height` properties searchBar's style otherwise the bar doesn't show up. 

<img width="282" alt="screen shot 2015-10-09 at 11 24 55" src="https://cloud.githubusercontent.com/assets/3106676/10390361/6a62b708-6e78-11e5-8789-6ac1203044c2.png">

The problem is the `marginTop` property move down my `ListView` component. I don't understand my I need to specify `marginTop` and `height` properties.

Here is my code:

```
import React, { View, Component, StyleSheet, ListView, PropTypes, Text } from 'react-native';

import SearchBar from 'react-native-search-bar';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  searchBar: {
    marginTop: 64,
    height: 44,
    backgroundColor: 'green',
  },
  listView: {
    backgroundColor: 'red',
  },
});

export default class ContactsComponent extends Component {
  static propTypes = { dataSource: PropTypes.object.isRequired }
  static defaultProps = { dataSource: new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2}) }
  state = { dataSource: this.props.dataSource.cloneWithRows(['User 1', 'User 2', 'User 3', 'User 4', 'User 5']) }

  render() {
    return (
      <View style={styles.container}>
        <SearchBar placeholder="Search"
          style={styles.searchBar}
          barTintColor="#87D3D3"
          textFieldBackgroundColor="#D5EFEF"
          tintColor="#D5EFEF" />
        <ListView style={styles.listView} dataSource={this.state.dataSource}
        renderRow={(rowData) => <Text>{rowData}</Text>} />
      </View>
    );
  }
}
```

Any suggestion? 

Best,
Jean

**Comment by umhan35** [comment]
This a bug of RN: https://github.com/facebook/react-native/issues/721. The ListView have to be the root view or you can do: `automaticallyAdjustContentInsets={false}`
