### ISSUE TITLE
showsCancelButton doesn't work after clicking "cancel"

### ISSUE THREAD

**Issue by sdemjanenko** [umhan35/react-native-search-bar#34]
When I focus into the Search box and then hit cancel and then focus back into the search box the cancel button is no longer on the screen.

**Comment by mastermoo** [comment]
i solved it with setting state like this:
<SearchBar
            onCancelButtonPress={() => this.setState({showsCancelButton: false})}
            onFocus={() => this.setState({showsCancelButton: true})}
            showsCancelButton={this.state.showsCancelButton}
          />

hope this helps

**Comment by sdemjanenko** [comment]
Thanks for the workaround. It doesn't seem like I should have to jump through all those hoops to accomplish this.  I think this behavior should be fixed within this library.

**Comment by cancan101** [comment]
:+1:

**Comment by eyaleizenberg** [comment]
The workaround doesn't work well because the cancel is supposed to animate from the side

**Comment by umhan35** [comment]
PR #80 should solve this issue. I'll wait @evollu for his response tomorrow and merge it.
