### ISSUE TITLE
Error; undefined is not an object (evaluating \'NativeModules.RNSearchBarManager.ComponentHeight\')

### ISSUE THREAD

**Issue by coderdave** [umhan35/react-native-search-bar#35]
I'm getting this error using react native 0.13.2 and react-native-search-bar 2.5.0

Specifically breaks on this line:
https://github.com/umhan35/react-native-search-bar/blob/master/SearchBar.js#L48

**Comment by coderdave** [comment]
Never mind. I needed to init a whole new project to fix this. :-1:

**Comment by zackhall** [comment]
@coderdave I'm also seeing the error. Do you mean you had to create a whole new project to be able to add in this SearchBar without the error?

**Comment by zackhall** [comment]
Solution from #37. 

`npm install rnpm -g`
`rnpm link`

**Comment by coderdave** [comment]
@zackhall I use to have to start a new project, but nowadays I just delete the `node_modules` directory, `npm cache clear` and `npm install`. Also, running `react-native upgrade` has been helpful to when going to a new version of react native.

**Comment by camslaz** [comment]
I ran into the same issue after installing the package and running `react-native link` for latest versions of react-native. I just killed the simulator, packet manager and relaunched with `react-native run-ios` and it solved the error.
