### ISSUE TITLE
React-Native v0.14.0: undefined is not an object (evaluating 'NativeModules.RNSearchBarManager.ComponentHeight')

### ISSUE THREAD

**Issue by gwyneplaine** [umhan35/react-native-search-bar#37]
This error occurs after upgrading from react-native v0.11 to react-native v0.14 
A brief description of my environment:

OS: OSX Yosemite v 10.10.4
XCode: v7.0.1 (7A1001)
Node: v4.1.2

**Comment by chapinkapa** [comment]
+1

**Comment by ibrens** [comment]
+1

**Comment by LaiYao** [comment]
+1

I get such error also.

**Comment by ruandao** [comment]
Do you forget this: http://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by DickyT** [comment]
Instead of linking libraries into XCode, just drag files (2 * `*.m` and 2 * `*.h` files) into your project can solve this

**Comment by ds1239** [comment]
@DickyT Thanks, that worked for me.

**Comment by zackhall** [comment]
@DickyT Thanks! Fixed the issue for me!

`npm install rnpm -g`
`rnpm link`

**Comment by umhan35** [comment]
As stated in issue #35, you need to link the library.

**Comment by shenders13** [comment]
@DickyT, what did you mean by "2 * *.m and 2 * *.h files"?

I have this problem too.
