### ISSUE TITLE
Issue with react-native-0.15.0

### ISSUE THREAD

**Issue by kanerogers** [umhan35/react-native-search-bar#39]
Hi, there,

As of 0.15.0, the signature of `RCTEventDispatcher sendTextEventWithType` has changed. See [this commit](https://github.com/facebook/react-native/commit/6c7c845145e1da44ac5d965d49097eff1c11cc49#diff-1bbcacec5f18234fa10073eb3a8b8ce9R147).

As a workaround, I have modified `RNSearchBar.m` to pass a `key` of `nil`, as you aren't listening for the `onKeyPress` event, and this has got things working for me. But, if you want to implement this in the future, you might need to send back the text events being sent from `UISearchBar`.

**Comment by cancan101** [comment]
Would you mind putting up a PR for this?

**Comment by kanerogers** [comment]
Sure. Leave it with me.

**Comment by cancan101** [comment]
I PRed #45.

**Comment by kanerogers** [comment]
Thanks. :-)
