### ISSUE TITLE
How to Implement Hidden/Reveal Searchbar

### ISSUE THREAD

**Issue by cyprusglobe** [umhan35/react-native-search-bar#4]
@umhan35 
Wondering how we can go about adding pulldown searchbar?

![Pull Down Search](http://media.idownloadblog.com/wp-content/uploads/2014/03/iOS-7-Music-Searching.gif)

**Comment by umhan35** [comment]
I don't know exactly. It's probably better handled by Objective-C or Swift code. For pure JS, check out the [ScrollView](http://facebook.github.io/react-native/docs/scrollview.html)'s onScroll and the [animation guide](http://facebook.github.io/react-native/docs/animations.html#content) on React Native's website.

StackOverflow is a better place to ask this kind of question. Search "pull search bar ios" on Google :)
