### ISSUE TITLE
how to set caret color?

### ISSUE THREAD

**Issue by eyaleizenberg** [umhan35/react-native-search-bar#40]
Right now it's white, I need to change it to a different color. Throughout my app it's blue...

**Comment by eyaleizenberg** [comment]
my bad... passed the wrong parameter

**Comment by eyaleizenberg** [comment]
OK, my issue like this:
1. I want to set the tintColor to a certain color and I used the tintColor prop for it.
2. When I use the tintColor prop, the cancel button's tint also changes...

help?

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
