### ISSUE TITLE
Is there a maxWidth set on the search bar?

### ISSUE THREAD

**Issue by jossmac** [umhan35/react-native-search-bar#44]
I'm building a landscape iPad app and am using the searchbar at full width, it appears to max-out at `1000px`

**Comment by umhan35** [comment]
Yes, see here https://github.com/umhan35/react-native-search-bar/blob/master/RNSearchBar.m#L18

Probably you can find a workaround solution there.

**Comment by jossmac** [comment]
Okay, thanks for the that.

Is there any reason you settled on 1000, why not 1024?

**Comment by umhan35** [comment]
Because I was only developing a portrait iPhone app. I think we can programmingly get the width of the device, something like this: http://stackoverflow.com/a/3655117/390014. I don't have an iPad or a bigger device to test on. But you are welcome to try and contribute :)
