### ISSUE TITLE
React-Native 0.16.0: 'RCTSparseArray.h' file not found

### ISSUE THREAD

**Issue by ibrens** [umhan35/react-native-search-bar#47]
According to some highlights of the release here: 
http://www.reactnative.com/react-native-v0-16-0-rc-and-v0-15-0-released/

RCTSparseArray was replaced by NSDictionary. 

Will you upgrade?

**Comment by ivesy85** [comment]
I too am encountering this issue. Is there a quick fix I can implement?

**Comment by JonnyBGod** [comment]
+1

**Comment by DickyT** [comment]
Editing the `RNSearchBarManager.m` file, and change the `RCTSparseArray` in last 2 method into `NSDictionary`, then delete the `#import "RCTSparseArray.h"` could solve this problem.

But I encountered into another problem, which said that `undefined is not an object, evaluating NativeModules.RNSearchBarManager.ComponentHeight`

**Comment by tigershen23** [comment]
Same issue :(

**Comment by DickyT** [comment]
@tigershen23 see my solution, it works like a charm

**Comment by yuyaohshimo** [comment]
+1

**Comment by umhan35** [comment]
Fixed in #49 & Pushed to npm :)
