### ISSUE TITLE
Blur away keyboard

### ISSUE THREAD

**Issue by PhilippKrone** [umhan35/react-native-search-bar#5]
Hello,

I'm using the search bar to filter a listview on change of the search bar text. Is there currently any way implemented to hide the keyboard the moment I press something in the listview - like a blur() function?

Thanks
Philipp

**Comment by PhilippKrone** [comment]
Sorry, forgot to write my current solution:

var RCTUIManager = require('NativeModules').UIManager;
  blur: function() {
    RCTUIManager.blur(React.findNodeHandle(this.refs.searchbar));
  },

**Comment by umhan35** [comment]
Hi @PhilippKrone Check out the `keyboardDismissMode` of `ScrollView `: http://facebook.github.io/react-native/docs/scrollview.html#keyboarddismissmode. It should theretically work for `ListView` too because it's implemented on top of `ScrollView`.

**Comment by umhan35** [comment]
Closed as there is more than 1 week without response. Feel free to reopen it.
