### ISSUE TITLE
Cannot read property 'ComponentHeight' of undefined

### ISSUE THREAD

**Issue by fakefish** [umhan35/react-native-search-bar#57]
rn version: 0.17

search-bar version: 2.8

with basic usage.

// 原来是中国人哈

**Comment by CoericK** [comment]
@fakefish Any solution?

**Comment by nickw** [comment]
@fakefish same issue here - can you reopen or post your solution?

**Comment by nickw** [comment]
@fakefish @CoericK sorry, it's clear in the README that you need to add the files in Xcode:

> To link this library, please follow the first two steps in the Linking Libraries (iOS) guide on React Native website. The .xcodeproj file is in node_modules/react-native-search-bar/. In the end, you should have RNSearchBar.xcodeproj in the Libaries group on Xcode and libRNSearchBar.a in the Link Binary With Libraries section inside the Build Phases tab of your project target.

**Comment by fakefish** [comment]
@nickw yeah, I forgot how I solve this problem, it should be the same as yours.

**Comment by mshaaban0** [comment]
the easiest way `rnpm link`

**Comment by joncursi** [comment]
run `rnpm link`, and don't forget to restart the packager and rebuild the app on simulator

**Comment by atdrago** [comment]
I just ran into this as well. Along with the above, make sure your scheme's build configuration is set to "Debug".

1. Product > Scheme > Edit Scheme...
2. Click the Run tab
3. Set "Build Configuration" to "Debug"
