### ISSUE TITLE
Hide keyboard on search and cancel.

### ISSUE THREAD

**Issue by mauron85** [umhan35/react-native-search-bar#59]
Hi,

i'm struggling with keyboard that is not hidden when search is tapped on keyboard and also when cancel button (X) is tapped withing search bar.

I've googled out how to hide keyboard on search, by adding 
```[searchBar resignFirstResponder];``` into searchBarSearchButtonClicked method,

but adding same line to searchBarCancelButtonClicked doesn't hide the keyboard.

**Comment by cajoy** [comment]
+1

**Comment by cajoy** [comment]
You can do it by adding ref. Check the following example. 

```
    _onPressSearchButton: function () {
        this.refs.searchbar.blur();
    },

  render: function () {
    return (
                  <SearchBar
                    placeholder='Search'
                    ref="searchbar"
                    onSearchButtonPress={this._onPressSearchButton}
                    />
```

**Comment by noumansakhawat-dev** [comment]
You can do it by adding ref. Check the following example.

```
    _onPressSearchButton: function () {
        this.refs.searchbar.current.blur();
    },

  render: function () {
    return (
                  <SearchBar
                    placeholder='Search'
                    ref="searchbar"
                    onSearchButtonPress={this._onPressSearchButton}
                    />
```
