### ISSUE TITLE
Can't remove top border

### ISSUE THREAD

**Issue by coderdave** [umhan35/react-native-search-bar#6]
I'm trying to imitate the behavior where you click the Search Bar and it moves to the top of the screen, which is working for me so far, but how do you remove the top border?
![ios_simulator_-_iphone_5s_-_iphone_5s___ios_8_4__12h141_](https://cloud.githubusercontent.com/assets/964751/8632016/3349a704-2756-11e5-8a97-271b432eba82.png)

**Comment by umhan35** [comment]
Could you show me the code for the functionality?

**Comment by coderdave** [comment]
I'm using a Header component where if the search bar is focused, it hides the navigation bar. Here's the main render function:
```
render(){
    return (
      <View style={this.headerStyle()}>
        <View style={this.topBorderStyle()}></View>
        {this.state.searchBarFocused && this.props.searchBar ? null :
          <View style={styles.navBar}>
            <View style={styles.leftComponent}>{this.props.leftComponent}</View>
            <View style={styles.middleComponent}>{this.props.middleComponent}</View>
            <View style={styles.rightComponent}>{this.props.rightComponent}</View>
          </View>
        }
        {this.props.searchBar ?
          <SearchBar style={this.searchBarStyle()} onFocus={this.searchBarFocused} placeholder='Search'
            onSearchButtonPress={this.onSearchButtonPress}
            onCancelButtonPress={this.onCancelButtonPress}
            onChangeText={this.onChangeText} />
          : null
        }
      </View>
    );
  }
```

**Comment by piyushchauhan2011** [comment]
@coderdave I noticed that you used `style` props in `<SearchBar />`, does it work ? styling the search bar ?

**Comment by coderdave** [comment]
I've tried borderTopStyle: 'none' but no effect.

**Comment by chengs** [comment]
An alternative solution is set hideBackground=true and put the search bar into a view component. Then you can set the properties of that view.

**Comment by Mokto** [comment]
Thx @chengs works perfectly !

**Comment by eyaleizenberg** [comment]
@chengs Thanks!
