### ISSUE TITLE
Does it work with android? 

### ISSUE THREAD

**Issue by ahmed1490** [umhan35/react-native-search-bar#60]
If so, then its good to mention.
If not, still worth mentioning in the Readme.md

**Comment by umhan35** [comment]
It's mentioned in the first line of README: "The high-quality iOS native search bar for react native."

**Comment by ahmed1490** [comment]
The confusing part is...
1. It could mean its only ios native search bar available for ios
OR
2. The project provides ios like search bar for react native in general

**Comment by umhan35** [comment]
It doesn't have the second meaning.
