### ISSUE TITLE
Programmatically clear the input?

### ISSUE THREAD

**Issue by Jeiwan** [umhan35/react-native-search-bar#65]
Is it possible to programmatically clear the search bar input field? Something similar to `setNativeProps({text: ''})` for `TextInput` component?

**Comment by ghamaide** [comment]
+1

**Comment by itinance** [comment]
+1

**Comment by bantisk** [comment]
+1

**Comment by gkueny** [comment]
+1

**Comment by kuldeepantil** [comment]
+1

**Comment by iRoachie** [comment]
Implemented in https://github.com/umhan35/react-native-search-bar/pull/133/commits/4749a909f5c272a7fdaaac10d46cf506be47bb66, will be available in the next release

**Comment by iRoachie** [comment]
Released in [v3.2.0](https://github.com/umhan35/react-native-search-bar/releases/tag/v3.2.0). You can use the `clearText` method to accomplish this.

First make a ref, then you can call the method `this.refs.searchBar.clearText();`
