### ISSUE TITLE
cancel button doesn't show on the second time

### ISSUE THREAD

**Issue by evollu** [umhan35/react-native-search-bar#71]
I set `showsCancelButton={true}` and it works correctly at the first time.
But after I click cancel and focus again, the cancel button doesn't show up. The value in UISearchBar is overwritten by `[self setShowsCancelButton:NO animated:YES];`

**Comment by umhan35** [comment]
I'll now take a look. Sorry for the delay.

**Comment by umhan35** [comment]
Solved in PR #79
