### ISSUE TITLE
Let other people help you

### ISSUE THREAD

**Issue by Mokto** [umhan35/react-native-search-bar#76]
Hi @umhan35, 

I see there are a lot of on-going issues and pull requests on this great plugin.

Would you mind giving someone (I can do it if you want) write access to help you with it ?

Thanks !

**Comment by umhan35** [comment]
Hi @Mokto, thanks for trying to helping out. But you don't need write access to help. Most of issues are open because they are questions more suitable to post on StackOverflow.

**Comment by Mokto** [comment]
Well, thanks for your quick answer !

Looking forward to see this nice plugin evolve ;)
