### ISSUE TITLE
Cancel button appears on open

### ISSUE THREAD

**Issue by KishPatel1996** [umhan35/react-native-search-bar#84]
The cancel button appears on app launch, but the text is not tinted.  Tapping the bar after tints the text.  Anyone know what may be causing this?

**Comment by michaelhelvey** [comment]
That's the default behavior for the `UISearchBar` component.  This library simply wraps the `UISearchBar` component, to provide true native behavior.  For example, in the following iOS code:

```objective-c
UISearchBar *bar = [[UISearchBar alloc] init];
bar.showsCancelButton = YES;
bar.tintColor = [UIColor greenColor];
[self.view addSubview:bar];
[bar setFrame:CGRectMake(0, 20, self.view.frame.size.width, 50)];
```

Here, the cancel button will start as gray (disabled), and when the `UITextField` assumes first responder, it will become `[UIColor greenColor]`.

**Comment by KishPatel1996** [comment]
@michaelhelvey  Interesting, thanks for the insight.  Do you know of a way to have the bar initially not have 'cancel' showing?

**Comment by KishPatel1996** [comment]
Figured it out.  Set showCancelButton on true in the callback for onFocus.

Thanks for the great library!

**Comment by iRoachie** [comment]
@KishPatel1996 How did you manage to do this?

**Comment by patrickdinary** [comment]
This might be a dumb question, but can you explain how you set showsCancelButton in the callback? Thanks!

**Comment by iRoachie** [comment]
@patrickdinary I keep a focus property in my state. Every time the input gets focus I change the property.

```jsx
showsCancelButton={this.state.focus}
onFocus={() => this.setState({focus: true})}

```

**Comment by patrickdinary** [comment]
Great, thank you so much!
