### ISSUE TITLE
KeyboardDismissMode

### ISSUE THREAD

**Issue by PickHoon** [umhan35/react-native-search-bar#85]
Hi, may I know what can I do to dismiss the keyboard other than click on the "cancel" button? I tried to use TouchableWithoutFeedback, but it failed to work as expected.

**Comment by michaelhelvey** [comment]
The library provides `unFocus` and `blur` methods for total control over when the keyboard shows/hides.  See [the docs](https://github.com/umhan35/react-native-search-bar#managing-the-keyboard).

**Comment by PickHoon** [comment]
Thanks @michaelhelvey for the replied. I had tried to show the search result by using listview. Now I found out that when I wished to dismiss the keyboard when I am scrolling the listview item, I have to add in keyboardDismissmode="on-drag" and keyboardShouldPersistTaps={false} in the listview.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks

**Comment by unmec** [comment]
To make the FlatList that contains search results work well with keyboard :-)

```
<SearchBar
  ref='searchBar'
  onSearchButtonPress={() => this.refs.searchBar.unFocus()}
/>

<FlastList
  keyboardDismissmode='on-drag'
/>
```
