### ISSUE TITLE
Delay on Keyboard Hide

### ISSUE THREAD

**Issue by luco** [umhan35/react-native-search-bar#89]
Do you guys see a little delay while dismissing the keyboard?
I don't see this while dismissing with `keyboardDismissMode='on-drag'`

```
<ScrollView style={styles.container}  automaticallyAdjustContentInsets={false} keyboardDismissMode='on-drag' keyboardShouldPersistTaps={false}>
            <SearchBar
                ref='searchBar'
                placeholder='Buscar'
                onSearchButtonPress={(event)=>{
                  this.refs.searchBar.unFocus()
                  this.refs.searchBar.blur()
                }}/>
            <View>
              <Text>Test</Text>
            </View>
          </ScrollView>
```

Also, when I search for something, tap on X, I cant unfocus from it, since my Search button is disabled.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
