### ISSUE TITLE
How can I style the search bar ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [umhan35/react-native-search-bar#9]
Can you provide me with an example of styling the search bar because when try to use `style={{ backroundColor: '#FAFAFA' }}` then, search bar disappears.

**Comment by zedman** [comment]
So it seems like you cant. I did it by modifying the source myself.
You need 'barTintColor' which you can define just as 'tintColor' has been defined in 3 files:
https://github.com/umhan35/react-native-search-bar/search?utf8=%E2%9C%93&q=tintColor&type=Code

**Comment by Snaddu** [comment]
I did solve this same problem by adding customStyles prop to search bar.

So on search bar render function i added new prop on style attribute. On customStyles prop i have {backgroundColor: '#ffffff'}. What do you think about this solution? I think this gives quite much more freedom on developing.

`<RNSearchBar
      style={[{height: NativeModules.RNSearchBarManager.ComponentHeight}, this.props.customStyles]}
      onChange={this._onChange}
      onPress={this._onPress}
      {...this.props}
    />;`

**Comment by Showyilu** [comment]
If you set hideBackground=true, and wrap the SearchBar with a View, you can style the background anyway you like
