### ISSUE TITLE
What about android?

### ISSUE THREAD

**Issue by waleedarshad-vf** [umhan35/react-native-search-bar#91]
Please provide support for android as well

**Comment by yezongyang** [comment]
+1

**Comment by lin493369** [comment]
+1

**Comment by AlisonWonderlandApps** [comment]
+1

**Comment by faogustavo** [comment]
+1?

**Comment by raghuureddy** [comment]
+1

**Comment by seanseany** [comment]
+1

**Comment by iRoachie** [comment]
Hey guys! Closing this as non-actionable for now. Currently the library is a port of UISearchBar to react -native. Although not impossible, it's very unlikely that android will be supported.
